<?php
/**
 *          ***********************************************************
 *          **********************||  SMART DASH   ||******************
 *          ***********************************************************
 * 
 *          @date               2019-11-15
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2019-2020 Burton Technology https://burtonservers.com
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Custom admin dashboard for easy lightweight SPA deployment.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */


/* * **** PURIFICAMOS VARIABLES ****** */

function broom($type, $string) {
    if ($type == "reg") { /* FILTRAR a - Z Y ESPACIOS */
        return preg_replace("/[^ \w]+/", "", $string);
    }
    if ($type == "text") { /* FILTRAR SOLO TEXTO PARA LECTURA SIN CARCTERES ESPECIALES */
        return preg_replace('#[^\p{L}\s-]#u', '', $string);
    }
    if ($type == "num") { /* FILTRAR TODO MENOS NUMEROS */
        return preg_replace('/\D/', '', $string);
    }
    if ($type == "spa") { /* CONVERTIR A ESPAñL */
        return preg_replace('#[^\p{L}\s-]#u', '', $string);
    }
    if ($type == "url") { /* TEXTO PARA URL */
        return str_replace('+', '_', urlencode(preg_replace("/[^ \w]+/", "", $string)));
    }
    if ($type == "voucher") { /* FILTRAR VOUCHER DE RED ALERTA */
        $clean = array("[", "\"", "]");
        return explode(',', str_replace($clean, '', $string));
    }
    if ($type == "syntec") { /* PARA NOMBRES TECNOMEGA*/     
        return preg_replace('/[^\p{L}0-9\-\.]/', ' ', preg_replace('(&#8221;)', ' ', $string));
    }
}


/*
 * +++++++++++++++++++++++      VIDEO ALEATORIO DE BACKGROUND       +++++++++++++++++++++++
 */
function getBGVideo() {
    $r = rand(1, 14);
    switch ($r) {
        case 1: $video = "wTeKnXaOmjg";// CIRCUIT SPARKLIN 
            break;
        case 2: $video = "7hiLrRaC2Ps";// CIRCUIT FLOW LIGHT
            break;
        case 3: $video = "bZpBOItNVwM";// INK DROPS
            break;
        case 4: $video = "RCZPsCjAbEU"; // BLUE SPACE CLOUDS 
            break;
        case 5: $video = "volsw7nOvvk"; // BLUE PARTICLES
            break;
        case 6: $video = "IxFxsq-ANpY"; // Smoke Trail
            break;
        case 7: $video = "LcF6ut-1M94"; // IRESTORM
            break;
        case 8: $video = "KGlWaG4N4L8"; // GOLDNE SPARKS
            break;
        case 9: $video = "MoQEPx30KHQ"; // GOLDNE SPARKS FLOATING
            break;
        case 10: $video = "lJf9GdAEy-A"; // BLUE FALLING VECTORS
            break;
        case 11: $video = "1ghLEigenZM"; // ORANGE PARTICLES
            break;
        case 12: $video = "UWF7dZTLW4c"; // SWAMP
            break;
        case 13: $video = "iE4pMhb8wjc"; // RINGS
            break;
        case 14: $video = "wOouUV1m5Wo"; // BONFIRE
            break;
    }   
    // $video = "volsw7nOvvk"; // STATIC VIDEO
    $code = '<div class="video-background">
                <div class="video-foreground">
                    <iframe src="https://www.youtube.com/embed/' . $video . '?controls=0&showinfo=0&rel=0&mute=1&modestbranding=1&autoplay=1&loop=1&playlist=' . $video . '" frameborder="0" allowfullscreen></iframe>
                </div>
                <div class="video-overlay"></div>
            </div>';
    return $code;
}

/** 
 * +++++++++++++++++++++++      GUARDAR VISITA DE USUARIO EN LA BASE DE DATOS       +++++++++++++++++++++++
 */
function trackvisitor($page) {
    $tracking_page_name = $page;
    if (isset($_SERVER['HTTP_REFERER'])) {
        $ref = $_SERVER['HTTP_REFERER'];
    } else {
        $ref = "DIRECTO";
    }
    $agent = $_SERVER['HTTP_USER_AGENT'];
    $ip = $_SERVER['REMOTE_ADDR'];
    $host_name = gethostbyaddr($_SERVER['REMOTE_ADDR']);
    $query = "INSERT INTO tb_track(tm, ref, agent, ip, tracking_page_name, domain, ip_value)    VALUES('" . date('Y-m-d') . "','$ref','$agent','$ip','$tracking_page_name','$host_name','" . date('H:i:s') . "')";
    $track = mysqli_query($link, $query) or die("no inserto" . mysqli_error($link));
}

/**
 * +++++++++++++++++++++++      CUSTOM FILTERS       +++++++++++++++++++++++
 */
function sanitize($string) {
    $string = str_replace(' ', '--', $string);
    $string = str_replace('.', '-DOT-', $string);
    $string = str_replace('@', '-AT-', $string);
    return preg_replace('/[^\p{L}0-9\-\.]/', '', $string);
}
?>